[package]
name = "check_vuids"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vk-safe-sys = { path="../vk-safe-sys", features=["vuid"] }